project:
  type: website

website:
  title: "Raeed Chowdhury"
  navbar:
    title: "Raeed Chowdhury"
    right:
      - href: index.qmd
        text: home
      - href: research.qmd
        text: research
      - href: blog/index.qmd
        text: blog
      - href: resources.qmd
        text: resources
  page-footer:
    left: "© 2026 Raeed Chowdhury"
    center:
      - icon: github
        href: https://github.com/raeedcho
        aria-label: GitHub
      - text: "{{< fa brands google-scholar >}}"
        href: https://scholar.google.com/citations?user=Ab0Y1pwAAAAJ
        aria-label: Google Scholar
      - text: "{{< fa brands orcid >}}"
        href: https://orcid.org/0000-0002-5934-919X
        aria-label: ORCID
      - icon: bluesky
        aria-label: Bluesky
        href: https://bsky.app/profile/raeedcho.com
      - icon: linkedin
        href: https://www.linkedin.com/in/raeedcho/
        aria-label: LinkedIn
      - icon: envelope-fill
        href: mailto:raeed.chowdhury@gmail.com
        aria-label: Email
    right: "built with [quarto](https://quarto.org){target=_blank}"

format:
  html:
    theme: simplex
    css: styles.scss
    code-fold: true
    code-tools: false

execute:
  freeze: auto
